### ISSUE TITLE
Regression running analysis since #2322 was merged

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2367]
```
Details

These additional details were reported when the problem occurred.

Error loading impact layer.
'NoneType' object has no attribute 'id'
Diagnostics

In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1403, in completed report = self.show_results()
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1482, in show_results self.analysis.aggregator.layer)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1355, in add_above_layer index = self.layer_legend_index(existing_layer)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1382, in layer_legend_index layer_id = layer.id()
```
