### PR TITLE
fix #2367 - regression caused by #2322

### LINKED ISSUE #2367: Regression running analysis since #2322 was merged
```
Details

These additional details were reported when the problem occurred.

Error loading impact layer.
'NoneType' object has no attribute 'id'
Diagnostics

In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1403, in completed report = self.show_results()
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1482, in show_results self.analysis.aggregator.layer)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1355, in add_above_layer index = self.layer_legend_index(existing_layer)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1382, in layer_legend_index layer_id = layer.id()
```

### PR DESCRIPTION
**Pull request by timlinux**
Aggregation layer could be None if whole area aggregation is used...

### CODE REVIEW

**Comment by ismailsunni** [comment]
LGTM
